//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMS.Infrastructure.Localization.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to terminate this session?.
        /// </summary>
        public static string AreYouSureYouWantToTerminateThisSession {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToTerminateThisSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client successfully created..
        /// </summary>
        public static string ClientSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ClientSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client successfully deleted..
        /// </summary>
        public static string ClientSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ClientSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client successfully updated..
        /// </summary>
        public static string ClientSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ClientSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Client failed..
        /// </summary>
        public static string CreatingClientFailed {
            get {
                return ResourceManager.GetString("CreatingClientFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Role failed..
        /// </summary>
        public static string CreatingRoleFailed {
            get {
                return ResourceManager.GetString("CreatingRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating siloItem failed..
        /// </summary>
        public static string CreatingSiloItemFailed {
            get {
                return ResourceManager.GetString("CreatingSiloItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating user failed..
        /// </summary>
        public static string CreatingUserFailed {
            get {
                return ResourceManager.GetString("CreatingUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By confirming this operation, all the data related to the client including all the information related to the temperature history of the sensors, as well as the information related to the mapping (configuration) of the project will be deleted and cannot be recovered.
        ///
        ///Are you sure you want to confirm this operation ?.
        /// </summary>
        public static string DeleteAllSiloItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteAllSiloItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All silo items have been successfully deleted..
        /// </summary>
        public static string DeleteAllSiloItemsCompletedSuccessfull {
            get {
                return ResourceManager.GetString("DeleteAllSiloItemsCompletedSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all silo items failed..
        /// </summary>
        public static string DeleteAllSiloItemsFailed {
            get {
                return ResourceManager.GetString("DeleteAllSiloItemsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By confirming this operation, all data related to this {0} ,including information related to mapping (configuration) and temperature history will be irreversibly deleted.
        ///
        ///Are you sure you want to confirm this operation?.
        /// </summary>
        public static string DeleteSiloItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteSiloItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting SiloItem failed..
        /// </summary>
        public static string DeleteSiloItemFailed {
            get {
                return ResourceManager.GetString("DeleteSiloItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiloItem successfully deleted..
        /// </summary>
        public static string DeleteSiloItemSuccessfull {
            get {
                return ResourceManager.GetString("DeleteSiloItemSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Client failed..
        /// </summary>
        public static string DeletingClientFailed {
            get {
                return ResourceManager.GetString("DeletingClientFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting role failed..
        /// </summary>
        public static string DeletingRoleFailed {
            get {
                return ResourceManager.GetString("DeletingRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user failed..
        /// </summary>
        public static string DeletingUserFailed {
            get {
                return ResourceManager.GetString("DeletingUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your Password?.
        /// </summary>
        public static string DoYouForgotPassword {
            get {
                return ResourceManager.GetString("DoYouForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete Client? This process cannot be undone..
        /// </summary>
        public static string DoYouReallyWantToDeleteClient {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &apos;{0}&apos;? Users who have this role will be restricted..
        /// </summary>
        public static string DoYouReallyWantToDeleteRole {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &apos;{0}&apos;? All data releated to this user will be deleted too..
        /// </summary>
        public static string DoYouReallyWantToDeleteUser {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address linked to your account and you will recive an email containing a link to reset your password..
        /// </summary>
        public static string EnterEmailToReciveForgotPasswordCode {
            get {
                return ResourceManager.GetString("EnterEmailToReciveForgotPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the terms and conditions..
        /// </summary>
        public static string IhaveReadAndAgreeToTheTermsAndConditions {
            get {
                return ResourceManager.GetString("IhaveReadAndAgreeToTheTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        public static string NotAuthorizedToAccessThisResource {
            get {
                return ResourceManager.GetString("NotAuthorizedToAccessThisResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a data system to continue.
        /// </summary>
        public static string PleaseSelectClientToContinue {
            get {
                return ResourceManager.GetString("PleaseSelectClientToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successfully completed..
        /// </summary>
        public static string RegisterSuccessfull {
            get {
                return ResourceManager.GetString("RegisterSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. please try again..
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role successfully created..
        /// </summary>
        public static string RoleSuccessfullyCreated {
            get {
                return ResourceManager.GetString("RoleSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role successfully deleted..
        /// </summary>
        public static string RoleSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("RoleSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role successfully updated..
        /// </summary>
        public static string RoleSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("RoleSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session successfully terminated..
        /// </summary>
        public static string SessionSuccessfullyTerminated {
            get {
                return ResourceManager.GetString("SessionSuccessfullyTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SiloItem successfully added..
        /// </summary>
        public static string SiloItemsSuccessfullyAdded {
            get {
                return ResourceManager.GetString("SiloItemsSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiloItem successfully added..
        /// </summary>
        public static string SiloItemSuccessfullyAdded {
            get {
                return ResourceManager.GetString("SiloItemSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiloItem successfully updated..
        /// </summary>
        public static string SiloItemSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SiloItemSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating session failed..
        /// </summary>
        public static string TerminatingSessionFailed {
            get {
                return ResourceManager.GetString("TerminatingSessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect..
        /// </summary>
        public static string TheUsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("TheUsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Client failed..
        /// </summary>
        public static string UpdatingClientFailed {
            get {
                return ResourceManager.GetString("UpdatingClientFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Role failed..
        /// </summary>
        public static string UpdatingRoleFailed {
            get {
                return ResourceManager.GetString("UpdatingRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating siloItem failed..
        /// </summary>
        public static string UpdatingSiloItemFailed {
            get {
                return ResourceManager.GetString("UpdatingSiloItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating user failed..
        /// </summary>
        public static string UpdatingUserFailed {
            get {
                return ResourceManager.GetString("UpdatingUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem updating the user account..
        /// </summary>
        public static string UserAccountNotUpdated {
            get {
                return ResourceManager.GetString("UserAccountNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully updated..
        /// </summary>
        public static string UserAccountUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserAccountUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        public static string UserPasswordChangeSuccessfully {
            get {
                return ResourceManager.GetString("UserPasswordChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the password encountered an error..
        /// </summary>
        public static string UserPassworNotUpdated {
            get {
                return ResourceManager.GetString("UserPassworNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        public static string UserSuccessfullyCreated {
            get {
                return ResourceManager.GetString("UserSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted..
        /// </summary>
        public static string UserSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UserSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully updated..
        /// </summary>
        public static string UserSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("UserSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        public static string YouAreNotAuthorizedToAccessThisResource {
            get {
                return ResourceManager.GetString("YouAreNotAuthorizedToAccessThisResource", resourceCulture);
            }
        }
    }
}
